### ISSUE TITLE
[EngAut] Automate Sync/Release the polakdot-sdk templates

### ISSUE THREAD

**Issue by mordamax** [paritytech/eng-automation#6] opened 2024-03-06 15:59 UTC
Origin: https://github.com/paritytech/polkadot-sdk/issues/3155#issuecomment-1959387933

**Who has requested**: @kianenigma 

**OKR Q2 2024**: 
Objective 1: Improving the Polkadot developer experience
KR: New dev templates are shipped as independent repositories automatically upon each stable release with source of truth in polkadot-sdk

**Problem**:
https://github.com/paritytech/polkadot-sdk/issues/3155
The existence of substrate-developer-hub in itself is questionable in my opinion. It is not well maintained, and I much rather everything to be in /paritytech, and ideally in polkadot-sdk repo.

**Details**
From @kianenigma 
What we suggest doing is the following:
- Bring all templates of polkadot-sdk under one folder. /templates/solo-chain, /templates/parachain and /templates/minimal are the main 3. These are the source of truth and always kept up to date.
- Create repositories corresponding for each, called polkadot-sdk-solo-chain-template, polkadot-sdk-solo-parachain and polkadot-sdk-minimal-tempalte.
- Write a script that receives a commit hash somewhere in the stable branch as input, and mirrors the templates into their corresponding repo. This script needs to replace all Cargo.toml files to use the released crates.
- We run the above script upon each update of stable branch, i.e. every 3 month.

**Comment by rzadp** [comment] 2024-03-12 14:02
Requested Github bot creation: https://github.com/paritytech/security/issues/45

**Comment by rzadp** [comment] 2024-03-14 20:56
I have a first draft in the `paritytech-stg` organization.

The draft PR: https://github.com/paritytech-stg/polkadot-sdk/pull/24
The current result (minimal template): https://github.com/paritytech-stg/polkadot-sdk-minimal-template

---

I had to remove a dependency on [`frame`](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/Cargo.toml) because it is not available as a published crate.
Used `frame-*` and `sp-*` dependencies instead, and re-declared some types that were only available in `frame/src`.

@kianenigma Could you take a look and let me know if the direction I took makes sense?

**Comment by kianenigma** [comment] 2024-03-14 21:57
(cc-ing @gupnik as he might be faster to reply while I am attending to some urgent debugging)

I think now's the time to publish `frame` crate as well. Would be good to ask @EgorPopelyaev or @Morganamilo if it had any cargo-related issues? probably no reason, just because we didn't mark it.

**Comment by gupnik** [comment] 2024-03-15 04:44
Thanks @rzadp for looking into this. It seems that I don't have access to https://github.com/paritytech-stg/polkadot-sdk-minimal-template. Could you add me please?

> I had to remove a dependency on [frame](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/Cargo.toml) because it is not available as a published crate.

Yeah, I agree with @kianenigma to publish the `frame` crate instead of removing it altogether. Let me know if I can help in any way.

**Comment by rzadp** [comment] 2024-03-15 07:57
> It seems that I don't have access to https://github.com/paritytech-stg/polkadot-sdk-minimal-template. Could you add me please?

Ah right, made it public now @gupnik

**Comment by rzadp** [comment] 2024-03-15 11:42
I have a problem building the current result template, I'm missing a `ExtrinsicInclusionMode` enum because it does not exists (yet) in the released `sp_runtime` crate.

@gupnik Are you able to help with that?

The real problem is that with the automation, I'm trying to use released crates from `release-crates-io-v1.8.0` branch, using the template code from `master`. I cannot run the automation from the release branch yet, because the templates didn't exist in the monorepo back then.

---

Shall we wait until:
- The next crates release, which will include the templates code that works properly with the released code.
- `frame` crate starts being released.
- @kianenigma I see you also have some [ongoing work](https://github.com/paritytech/polkadot-sdk/pull/3597) changing the templates?

Or shall I keep working on it with what we have presently?

**Comment by gupnik** [comment] 2024-03-15 12:08
@rzadp I think we need to get the `frame` crate released. Can we do that please?

**Comment by rzadp** [comment] 2024-03-15 13:22
@EgorPopelyaev @Morganamilo Could we have the `frame` crate released please?

**Comment by kianenigma** [comment] 2024-03-18 12:34
> @kianenigma I see you also have some https://github.com/paritytech/polkadot-sdk/pull/3597 changing the templates?

This is an experimental branch (as indicated by "DNM"), if finalized, it will be a new template, so feel free to work on the 3 that is already there.

**Comment by gupnik** [comment] 2024-03-21 06:19
@rzadp This has been published: https://crates.io/crates/polkadot-sdk-frame. Are we good to proceed?

**Comment by rzadp** [comment] 2024-03-21 09:49
> @rzadp This has been published: https://crates.io/crates/polkadot-sdk-frame. Are we good to proceed?

Great, I will try it out.

**Comment by rzadp** [comment] 2024-03-21 10:40
The crate is not a part of the most recent release branch `release-polkadot-v1.9.0`, so I will still have to do some additional dance around it.

**Comment by rzadp** [comment] 2024-03-21 10:52
Sent a PR to psvm to include `v1.9.0`: https://github.com/paritytech/psvm/pull/2

**Comment by rzadp** [comment] 2024-03-21 14:21
I got stuck trying to use this newly released crate. I'm probably doing something stupid, @gupnik could you give me a hand please?

To reproduce my issue:

```
git clone https://github.com/paritytech-stg/polkadot-sdk-minimal-template.git
cd polkadot-sdk-minimal-template
cargo +nightly build
```

Issue:

```
error: Could not find `frame-system` in `dependencies` or `dev-dependencies` in `<snip>/pallets/template/Cargo.toml`!
  --> pallets/template/src/lib.rs:10:1
   |
10 | #[polkadot_sdk_frame::pallet]
```

I don't think I should be changing the template and adding individual `frame-*` to dependencies?

---

It compiles fine when building inside the workspace.
Inside the workspace, I'm using a modified import and changed references from `frame` to `polkadot_sdk_frame`:

```diff
- frame = { path = "../../../../substrate/frame", default-features = false, features = ["experimental","runtime",] }
+ polkadot-sdk-frame = { package = "frame", path = "../../../../substrate/frame", default-features = false, features = ["experimental", "runtime"], version = "0.1.0" }
```

It is because the package is still [called `frame`](https://github.com/paritytech/polkadot-sdk/blob/3c3d6fceb82372a3019b37117aa453d564b212de/substrate/frame/Cargo.toml#L2) in the workspace.

The diff of my changes in the workspace is [here](https://github.com/paritytech-stg/polkadot-sdk/pull/24/files).

When yanked out of the workspace and using released crates, the aforementioned issue happens.

**Comment by gupnik** [comment] 2024-03-22 04:01
@rzadp I will take a look. Thanks.

**Comment by gupnik** [comment] 2024-03-22 04:57
Seems like this is caused by https://github.com/paritytech/polkadot-sdk/blob/ea5f4e9a4d78234eb68bbb9130a24b0598c7893a/substrate/frame/support/procedural/tools/src/lib.rs#L115 where we assume the crate's name to be `frame`. Will raise a PR with the fix soon. 

CC: @kianenigma in case you have something to add.

**Comment by gupnik** [comment] 2024-04-04 08:36
@rzadp https://github.com/paritytech/polkadot-sdk/pull/3813 is merged now. Could we proceed here please?

**Comment by rzadp** [comment] 2024-04-04 08:44
> @rzadp [paritytech/polkadot-sdk#3813](https://github.com/paritytech/polkadot-sdk/pull/3813) is merged now. Could we proceed here please?

Sure, I'll continue.

**Comment by rzadp** [comment] 2024-04-04 11:27
I've checked and all seems good for me, however to really proceed I'm gonna have to wait until a new crate release happens, that includes this PR.

**Comment by gupnik** [comment] 2024-04-04 16:05
> I've checked and all seems good for me, however to really proceed I'm gonna have to wait until a new crate release happens, that includes this PR.

@rzadp A new version has been published. Please let me know if you need anything else.

**Comment by rzadp** [comment] 2024-04-04 20:04
Hey @gupnik, I'm still running into exactly same issue as [described before](https://github.com/paritytech/eng-automation/issues/6#issuecomment-2012428997).

The reproduction is also the same - try to build the `master` of https://github.com/paritytech-stg/polkadot-sdk-minimal-template.

It has been updated to use the newly released crates, including `polkadot-sdk-frame@0.1.1`

The result is the same, no matter if I import it like this:

```
frame = { package = "polkadot-sdk-frame", version = "0.1.1", (...)

use frame;
```

Or like this:

```
polkadot-sdk-frame = { version = "0.1.1", (...)

use polkadot_sdk_frame;
```

**Comment by gupnik** [comment] 2024-04-05 05:52
@rzadp Seems that the `frame-support` has not been updated causing the release to still use the older deps. I have asked for another release for that as well. Hopefully that should fix it.

**Comment by gupnik** [comment] 2024-04-05 05:59
@rzadp Seems that one of the dependencies has not been updated yet: https://crates.io/crates/frame-support-procedural-tools. Have asked to get this fixed.

**Comment by gupnik** [comment] 2024-04-05 10:15
@rzadp This is fixed now.

**Comment by rzadp** [comment] 2024-04-05 10:41
> @rzadp This is fixed now.

Looks good, my `minimal` template now successfully builds outside of the monorepo, and can run a local dev chain 👍

Next I'll check the `parachain` and `solochain` templates.

**Comment by rzadp** [comment] 2024-04-09 10:27
Proposed a PR: https://github.com/paritytech/polkadot-sdk/pull/4040

**Comment by rzadp** [comment] 2024-04-13 14:12
The PR has been merged and tested out in `polkadot-sdk`.

Results:

- [minimal template](https://github.com/paritytech/polkadot-sdk-minimal-template)
- [parachain template](https://github.com/paritytech/polkadot-sdk-parachain-template)
- [solochain template](https://github.com/paritytech/polkadot-sdk-solochain-template)

---

Questions for next steps:

@kianenigma @gupnik Is there anything I can do further in order to improve those templates?

@EgorPopelyaev @Morganamilo What could be a trigger to turn it into a fully automatic job?
A push to a `release-crates-io-v*` branch? Note that the crates need to be already published when the job starts. Is there a tag that gets created when crate release finishes perhaps?

**Comment by PierreBesson** [comment] 2024-04-15 14:00
In addition to updating the standalone repos consistently. It would be good that each of those repos have proper CI pipelines set up for Continuous building and releasing. ping @lovelaced

We (Devops Team) are very interested in having those templates continuously released as binary and docker image so we can directly deploy and try to onboard them on a testnet for example. This is the closest we can get of e2e testing of a community parachain. This is important for keeping good support of those templates in our deployment tooling (ansible, helm-chart) and ensure a good devops experience for parachain teams.

Even better would be if the release team (ping @EgorPopelyaev) can build those templates in advance of them being synced to their own repos so we avoid syncing broken templates to the master branch of `paritytech/polkadot-sdk-*-template` where parachain teams will use it as a base of their parachain node.

**Comment by rzadp** [comment] 2024-04-15 14:51
> build those templates in advance of them being synced to their own repos so we avoid syncing broken templates

@PierreBesson In case you missed it - The templates are being build [before syncing](https://github.com/paritytech/polkadot-sdk/blob/8b4cfda7589325d1a34f70b3770ab494a9d4052c/.github/workflows/sync-templates.yml#L140), as well as [after syncing](https://github.com/paritytech/polkadot-sdk-minimal-template/blob/b218abb9bcb753708580311ef16a2b24ee5474e9/.github/workflows/ci.yml#L39).

**Comment by PierreBesson** [comment] 2024-04-16 11:27
@rzadp `cargo check && cargo test` is nice to do but it's not a release. We are not building the final binary and eg. testing it with Zombienet to validate that the parachain onboards properly.

**Comment by rzadp** [comment] 2024-04-22 12:02
I created [this PR](https://github.com/paritytech/polkadot-sdk/pull/4240) which we'll need to synchronize templates with recent version `1.10.0` and following ones.

@EgorPopelyaev Do you have a standard way of testing those templates inside the monorepo before a release, that could be re-used before syncing the templates? Could we collaborate on it?

**Comment by EgorPopelyaev** [comment] 2024-04-23 15:49
@rzadp Unfortunately, no, we don't have such tests in place for now.

**Comment by rzadp** [comment] 2024-04-23 16:08
Note: We agreed to kick off the synchronization job as part of the manual process upon the crate releases, for now.

**Comment by rzadp** [comment] 2024-04-24 14:28
The last version of `psvm` has introduced two problems for this workflow - with aliased import of crates, and apparently with build dependencies.

The problem can be seen in [this automated PR](https://github.com/paritytech-stg/polkadot-sdk-minimal-template/pull/8/files) - crates `frame/polkadot-sdk-frame` and `substrate-build-script-utils`. I'll be looking into it next week.

**Comment by rzadp** [comment] 2024-04-29 18:03
Note: the problem with `frame/polkadot-sdk-frame` seems to be caused by the fact that the crate is named `frame` on the `1.10.0` branch - but the (desired) name `polkadot-sdk-frame` is there on the `1.9.0` branch, and on `master`. I'm trying to figure out what happened.

**Comment by rzadp** [comment] 2024-04-29 18:25
Another note:

> The last version of psvm has introduced two problems for this workflow - with aliased import of crates, and apparently with build dependencies.

Correction - the problem is not only about build dependencies, but also regular dependencies. The newest version of `psvm` seems to not convert packages that previously worked - work example `sc-telemetry`. I'm trying to find a pattern which packages are not working, and why.

**Comment by rzadp** [comment] 2024-04-29 18:53
I have pinpointed the issues I'm having to `psvm` preferring to use `Plan.toml` for determining versions instead of `Cargo.lock` (as before).

The functionality to read `Cargo.lock` is still there (as a fallback) and it continues to work for my case.

I have asked [here](https://github.com/paritytech/psvm/pull/11#issuecomment-2083427008).

**Comment by rzadp** [comment] 2024-05-02 15:23
The issue with `psvm` has been overcome. (So my 4 previous comments above are resolved now).

And now we ran into another issue: https://github.com/paritytech/polkadot-sdk/issues/4347

**Comment by gupnik** [comment] 2024-05-04 11:06
> The issue with `psvm` has been overcome. (So my 4 previous comments above are resolved now).
> 
> And now we ran into another issue: [paritytech/polkadot-sdk#4347](https://github.com/paritytech/polkadot-sdk/issues/4347)

@rzadp Now that this is resolved, can we push an update please?

**Comment by rzadp** [comment] 2024-05-06 09:40
@gupnik Looks like we're almost there.

[minimal](https://github.com/paritytech/polkadot-sdk-minimal-template) and [solochain](https://github.com/paritytech/polkadot-sdk-solochain-template) templates have been just updated with version `1.11.0` and all seems well with those two.

However I've run into an issue with the parachain one (wonder when I'll stop running into issues with this task 😅)

It appears that [`parachain-template-runtime`](https://crates.io/crates/parachain-template-runtime) and [`pallet-parachain-template`](https://crates.io/crates/pallet-parachain-template) are published as crates, which conflicts with the usage of `psvm` tool which changes local dependencies to crate dependencies, but should not do it in this case.

I'm not sure why they're published - intentionally or some leftover?

I could add some workarounds to it - but first I'll try to figure out if those are needed on crates.io - if not, yanking them will solve my issue.

**Comment by gupnik** [comment] 2024-05-06 10:20
> [minimal](https://github.com/paritytech/polkadot-sdk-minimal-template) and [solochain](https://github.com/paritytech/polkadot-sdk-solochain-template) templates have been just updated with version 1.11.0 and all seems well with those two.

Thanks @rzadp. However, there's now a doc-only [crate](https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/Cargo.toml) that's not available in the minimal template. Similarly, it's not using the README.md from the repo. It seems that [this](https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/runtime/src/lib.rs) file is also not updated.

> It appears that [parachain-template-runtime](https://crates.io/crates/parachain-template-runtime) and [pallet-parachain-template](https://crates.io/crates/pallet-parachain-template) are published as crates, which conflicts with the usage of psvm tool which changes local dependencies to crate dependencies, but should not do it in this case.

But I do see that it has [`publish=false`](https://github.com/paritytech/polkadot-sdk/blob/73c89d308fefcedfc3619f0273e13b6623766b81/templates/parachain/runtime/Cargo.toml#L10). So, it should not have been published in the first place?

**Comment by rzadp** [comment] 2024-05-06 10:58
> But I do see that it has [`publish=false`](https://github.com/paritytech/polkadot-sdk/blob/73c89d308fefcedfc3619f0273e13b6623766b81/templates/parachain/runtime/Cargo.toml#L10). So, it should not have been published in the first place?

I would think so.
There is nothing wrong with this crate existing in `crates.io` on itself, but in our case it messes up the template when using `psvm`.
On the other hand there are downloads of this crate so I don't know. @EgorPopelyaev @Morganamilo any idea?

---

> Thanks @rzadp. However, there's now a doc-only [crate](https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/Cargo.toml) that's not available in the minimal template. Similarly, it's not using the README.md from the repo. It seems that [this](https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/runtime/src/lib.rs) file is also not updated.

Please look at `release-crates-io-v1.11.0` branch, not `master` - that's the source of the update.

**Comment by rzadp** [comment] 2024-05-06 11:01
> However, there's now a doc-only [crate](https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/Cargo.toml)

Ah, it'll probably cause issues when syncing the next release 🥲

**Comment by gupnik** [comment] 2024-05-06 11:28
> Please look at release-crates-io-v1.11.0 branch, not master - that's the source of the update.

I actually see only master.

<img width="1466" alt="Screenshot 2024-05-06 at 4 57 41 PM" src="https://github.com/paritytech/eng-automation/assets/17176722/9bd7da94-693f-43a2-b553-cb7996d8934a">

**Comment by gupnik** [comment] 2024-05-06 11:32
> > However, there's now a doc-only [crate](https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/Cargo.toml)
> 
> Ah, it'll probably cause issues when syncing the next release 🥲

Can we push that as well please? We are planning to use these templates for PBA and would be good to have the doc-only crate in there as well.

**Comment by rzadp** [comment] 2024-05-06 14:08
@gupnik I meant the `release-crates-io-v1.11.0` branch in `polkadot-sdk` - it's been branched out of `master` so does not contain all the recent changes from `master`. For example [readme](https://github.com/paritytech/polkadot-sdk/blob/release-crates-io-v1.11.0/templates/minimal/README.md) is still empty at that branch.

**Comment by rzadp** [comment] 2024-05-06 14:09
> Can we push that as well please? We are planning to use these templates for PBA and would be good to have the doc-only crate in there as well.

I'm not sure. In the other thread there is explicit discussion to remove it: https://github.com/paritytech/polkadot-sdk/issues/3155#issuecomment-2091451437
Also relevant piece: https://github.com/paritytech/polkadot-sdk/blob/73c89d308fefcedfc3619f0273e13b6623766b81/docs/sdk/Cargo.toml#L9-L10

**Comment by gupnik** [comment] 2024-05-06 14:23
> @gupnik I meant the release-crates-io-v1.11.0 branch in polkadot-sdk

Oh, got it. Thanks!

> > Can we push that as well please? We are planning to use these templates for PBA and would be good to have the doc-only crate in there as well.
> 
> I'm not sure. In the other thread there is explicit discussion to remove it: [paritytech/polkadot-sdk#3155 (comment)](https://github.com/paritytech/polkadot-sdk/issues/3155#issuecomment-2091451437) Also relevant piece: https://github.com/paritytech/polkadot-sdk/blob/73c89d308fefcedfc3619f0273e13b6623766b81/docs/sdk/Cargo.toml#L9-L10

@kianenigma What are your thoughts here?

**Comment by rzadp** [comment] 2024-05-07 10:00
> [minimal](https://github.com/paritytech/polkadot-sdk-minimal-template) and [solochain](https://github.com/paritytech/polkadot-sdk-solochain-template) templates have been just updated with version `1.11.0` and all seems well with those two.

Note: The issue with updating the [parachain](https://github.com/paritytech/polkadot-sdk-parachain-template) template should be resolved with a `1.12.0` release.

**Comment by rzadp** [comment] 2024-05-21 10:30
Note: The `1.12.0` has not appeared yet so I'm waiting for that.

**Comment by kianenigma** [comment] 2024-05-23 11:56
> It appears that [parachain-template-runtime](https://crates.io/crates/parachain-template-runtime) and [pallet-parachain-template](https://crates.io/crates/pallet-parachain-template) are published as crates, which conflicts with the usage of psvm tool which changes local dependencies to crate dependencies, but should not do it in this case.

> I'm not sure why they're published - intentionally or some leftover?

I don't see any reason to publish them, please make a PR to the base repo and mark them as unpunlish, thank you :)

**Comment by rzadp** [comment] 2024-05-23 12:45
> I don't see any reason to publish them, please make a PR to the base repo and mark them as unpunlish, thank you :)

@Morganamilo has yanked the crates, so this problem is already solved :) And in the repo they're already marked as unpublish.

**Comment by rzadp** [comment] 2024-05-27 09:31
After a [small fix in `psvm`](https://github.com/paritytech/psvm/pull/15), the synchronization has [worked with no issues](https://github.com/paritytech/polkadot-sdk/actions/runs/9251908584).

All templates got automatically updated to `1.12.0`.

**Comment by rzadp** [comment] 2024-05-31 10:20
Closing as completed - I'll still try to help with the source templates, but the automation of synchronization is done.

**Closed as completed by rzadp** 2024-05-31 10:20 UTC
